# Generated by Django 3.0.7 on 2020-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSSE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=60, null=True)),
                ('EmployeeName', models.CharField(max_length=60, null=True)),
                ('Designation', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('HSSE_Leader', 'HSSE_Leader'), ('Admin', 'Admin'), ('Pipe_Fitter', 'Pipe_Fitter'), ('Welder', 'Welder'), ('General_Fitter', 'General_Fitter')], max_length=60, null=True)),
                ('Group', models.CharField(choices=[('ALFA', 'ALFA'), ('HAB', 'HAB'), ('THIAM', 'THIAM'), ('PEC', 'PEC')], max_length=60, null=True)),
                ('Type', models.CharField(choices=[('Work_Related', 'Work_Related'), ('Non_Work_Related', 'Non_Work_Related')], max_length=60, null=True)),
                ('Remark', models.CharField(blank=True, max_length=60, null=True)),
                ('GivenDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone_Number',
            fields=[
                ('EmployeeID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=60, null=True)),
                ('Designation', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('HSSE_Leader', 'HSSE_Leader'), ('Admin', 'Admin'), ('Pipe_Fitter', 'Pipe_Fitter'), ('Welder', 'Welder'), ('General_Fitter', 'General_Fitter')], max_length=60, null=True)),
                ('Group', models.CharField(choices=[('ALFA', 'ALFA'), ('HAB', 'HAB'), ('THIAM', 'THIAM'), ('PEC', 'PEC')], max_length=60, null=True)),
                ('Type1', models.IntegerField(blank=True, choices=[('Grid', 'Grid'), ('Cellular', 'Cellular')], null=True)),
                ('Type2', models.IntegerField(blank=True, choices=[('Grid', 'Grid'), ('Cellular', 'Cellular')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='employeecourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='short_service_employee',
            name='id',
        ),
        migrations.AddField(
            model_name='bicycle_registration',
            name='BiCycle_No',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='in_house_training',
            name='Training',
            field=models.CharField(choices=[('Fire_Watchman', 'Fire_Watchman'), ('confined_space', 'confined_space'), ('cut_line_Tape', 'cut_line_Tape'), ('Rigger&Signalman', 'Rigger&Signalman'), ('Pipe_Fitter', 'Pipe_Fitter'), ('Welder', 'Welder'), ('General_Fitter', 'General_Fitter'), ('BA', 'Rigger&Signalman'), ('Turn_Around_Awareness', 'Turn_Around_Awareness'), ('Banksman', 'Banksman')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bicycle_registration',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='employeecourse',
            name='EmployeeID',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='in_house_training',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='short_service_employee',
            name='EmployeeID',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
